#Github Package Registry -used  the shared library was private
# https://npm.pkg.github.com

#This is now NPM Registry publish file
#https://registry.npmjs.org/

# name: Publish
name: Publish to NPM
on: 
  push: 
    branches: [main]
  pull_request:
    branches: [main]
jobs: 
  publish:
    runs-on: ubuntu-latest 
    permissions: 
      contents: read
      packages: write
    steps:  
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: 
          node-version: '22.x' 
          #this added for NPM Registry
          registry-url: 'https://registry.npmjs.org/'
          
      - run: npm install 
      - run: chmod +x ./node_modules/.bin/babel
      # GitHub Package Registry setup (no longer needed) -> For Private
      # - run:  |
      #     echo @VeckovN:https://npm.pkg.github.com/ > build/.npmrc  
      #     echo //npm.pkg.github.com/:_authToken=${{ secrets.NPM_TOKEN }} >> build/.npmrc }} >> build/.npmrc
      - run: npm run build
      - run: npm publish
        working-directory: ./build 
        env: 
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          # NPM_TOKEN: ${{ secrets.NPM_TOKEN  }}
        

